# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Description of what the lane does"
  lane :prodstore do
    gym(
      workspace: "FastlaneDemo.xcworkspace",
      scheme: "FastlaneDemo",
      configuration: "Release",
      clean: true,
      include_symbols: true,
      include_bitcode: false,
      skip_profile_detection: true,
      export_method: "app-store",
      output_name: "FastlaneDemo_Prod_appstore",
      xcargs: "OTHER_SWIFT_FLAGS=\"\$(inherited) \"-D\" \"Prod\"\"",
    )
  end

end
